package com.johnreah.accounts.springdatajpa;
// Generated 12 Nov 2021, 17:33:23 by Hibernate Tools 6.0.0.Alpha5

// JR

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,schema="public"
)
//JR
public class Account implements java.io.Serializable {


      @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    private Long id;
 
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_type_id")
    private AccountType accountType;
 
    
    @Column(name="description")
    private String description;
 
    
    @Column(name="balance", precision=17, scale=17)
    private Double balance;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="balance_timestamp", length=35)
    private Date balanceTimestamp;
 
    
    @Column(name="reference")
    private String reference;
 
@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    private Set<LinkCustomerAccount> linkCustomerAccounts = new HashSet<LinkCustomerAccount>(0);
 
@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    private Set<AccountHistory> accountHistories = new HashSet<AccountHistory>(0);

    public Account() {
    }

    public Account(AccountType accountType, String description, Double balance, Date balanceTimestamp, String reference, Set<LinkCustomerAccount> linkCustomerAccounts, Set<AccountHistory> accountHistories) {
       this.accountType = accountType;
       this.description = description;
       this.balance = balance;
       this.balanceTimestamp = balanceTimestamp;
       this.reference = reference;
       this.linkCustomerAccounts = linkCustomerAccounts;
       this.accountHistories = accountHistories;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public AccountType getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(AccountType accountType) {
        this.accountType = accountType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public Date getBalanceTimestamp() {
        return this.balanceTimestamp;
    }
    
    public void setBalanceTimestamp(Date balanceTimestamp) {
        this.balanceTimestamp = balanceTimestamp;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public Set<LinkCustomerAccount> getLinkCustomerAccounts() {
        return this.linkCustomerAccounts;
    }
    
    public void setLinkCustomerAccounts(Set<LinkCustomerAccount> linkCustomerAccounts) {
        this.linkCustomerAccounts = linkCustomerAccounts;
    }
    public Set<AccountHistory> getAccountHistories() {
        return this.accountHistories;
    }
    
    public void setAccountHistories(Set<AccountHistory> accountHistories) {
        this.accountHistories = accountHistories;
    }




}


