package com.johnreah.accounts.springdatajpa;
// Generated 12 Nov 2021, 17:33:23 by Hibernate Tools 6.0.0.Alpha5

// JR

import javax.persistence.*;
import java.util.Date;

/**
 * AccountHistory generated by hbm2java
 */
@Entity
@Table(name="account_history"
    ,schema="public"
)
//JR
public class AccountHistory  implements java.io.Serializable {


      @Id 

    
    @Column(name="id", unique=true, nullable=false)
    private long id;
 
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_id")
    private Account account;
 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_stamp", length=35)
    private Date timeStamp;
 
    
    @Column(name="account", precision=17, scale=17)
    private Double account_1;
 
    
    @Column(name="balance", precision=17, scale=17)
    private Double balance;
 
    
    @Column(name="description")
    private String description;

    public AccountHistory() {
    }

	
    public AccountHistory(long id) {
        this.id = id;
    }
    public AccountHistory(long id, Account account, Date timeStamp, Double account_1, Double balance, String description) {
       this.id = id;
       this.account = account;
       this.timeStamp = timeStamp;
       this.account_1 = account_1;
       this.balance = balance;
       this.description = description;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Date getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }
    public Double getAccount_1() {
        return this.account_1;
    }
    
    public void setAccount_1(Double account_1) {
        this.account_1 = account_1;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


