package com.johnreah.accounts.springdatajpa;
// Generated 12 Nov 2021, 17:33:23 by Hibernate Tools 6.0.0.Alpha5

// JR

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * AccountType generated by hbm2java
 */
@Entity
@Table(name="account_type"
    ,schema="public"
)
//JR
public class AccountType implements java.io.Serializable {


      @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    private Long id;
 
    
    @Column(name="description")
    private String description;
 
    
    @Column(name="reference")
    private String reference;
 
@OneToMany(fetch=FetchType.LAZY, mappedBy="accountType")
    private Set<Account> accounts = new HashSet<Account>(0);

    public AccountType() {
    }

    public AccountType(String description, String reference, Set<Account> accounts) {
       this.description = description;
       this.reference = reference;
       this.accounts = accounts;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }




}


