package com.johnreah.accounts.springdatajpa;
// Generated 12 Nov 2021, 17:33:23 by Hibernate Tools 6.0.0.Alpha5

// JR

import javax.persistence.*;

/**
 * LinkCustomerAccount generated by hbm2java
 */
@Entity
@Table(name="link_customer_account"
    ,schema="public"
)
//JR
public class LinkCustomerAccount  implements java.io.Serializable {


      @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="accountId", column=@Column(name="account_id") ), 
        @AttributeOverride(name="customerId", column=@Column(name="customer_id") ) } )
    private LinkCustomerAccountId id;
 
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_id", insertable=false, updatable=false)
    private Account account;
 
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", insertable=false, updatable=false)
    private Customer customer;

    public LinkCustomerAccount() {
    }

	
    public LinkCustomerAccount(LinkCustomerAccountId id) {
        this.id = id;
    }
    public LinkCustomerAccount(LinkCustomerAccountId id, Account account, Customer customer) {
       this.id = id;
       this.account = account;
       this.customer = customer;
    }
   
    public LinkCustomerAccountId getId() {
        return this.id;
    }
    
    public void setId(LinkCustomerAccountId id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }




}


