package com.johnreah.accounts.springdatajpa;
// Generated 12 Nov 2021, 17:33:23 by Hibernate Tools 6.0.0.Alpha5

// JR

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinkCustomerAccountId generated by hbm2java
 */
@Embeddable
//JR
public class LinkCustomerAccountId  implements java.io.Serializable {


 

    @Column(name="account_id")
    private Long accountId;
 

    @Column(name="customer_id")
    private Long customerId;

    public LinkCustomerAccountId() {
    }

    public LinkCustomerAccountId(Long accountId, Long customerId) {
       this.accountId = accountId;
       this.customerId = customerId;
    }
   
    public Long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }
    public Long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LinkCustomerAccountId) ) return false;
		 LinkCustomerAccountId castOther = ( LinkCustomerAccountId ) other; 
         
		 return ( (this.getAccountId()==castOther.getAccountId()) || ( this.getAccountId()!=null && castOther.getAccountId()!=null && this.getAccountId().equals(castOther.getAccountId()) ) )
 && ( (this.getCustomerId()==castOther.getCustomerId()) || ( this.getCustomerId()!=null && castOther.getCustomerId()!=null && this.getCustomerId().equals(castOther.getCustomerId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAccountId() == null ? 0 : this.getAccountId().hashCode() );
         result = 37 * result + ( getCustomerId() == null ? 0 : this.getCustomerId().hashCode() );
         return result;
   }   


}


